title: Open Pages For PRC Stakeholders
description: A simple site for PRC stakeholders to view and download documents.
theme: just-the-docs
nav_depth: 2
just_the_docs:
  custom_css:
    - assets/css/style.scss